#!/bin/bash
set -e
if [ ! -d "/lib/modules/$(uname -r)/updates/" ]
then
	mkdir "/lib/modules/$(uname -r)/updates/"
fi
cp -f /usr/lib/modules/*.ko "/lib/modules/$(uname -r)/updates/"
echo "Running depmod, please wait ..."
depmod -A
echo "done running depmod"

echo "loading modules ..."
#for file in /usr/lib/modules/*.ko
#keeping the order is important ....
mods=("axiom_mem_manager.ko" "axiom_mem_dev.ko" "axiom_netdev.ko")
for kmod in  ${mods[@]}
do
#	kmod=${file%%.ko}
#	kmod=${kmod##*/}
	echo "Loading $kmod ..."
#	insmod $kmod
	loaded="$(lsmod | grep ${kmod%%.ko})"
	if [ ! -z $loaded ]
	then
		rmmod $kmod
	fi
	insmod /usr/lib/modules/$kmod
done
echo "done loading modules"
