#!/bin/bash
#set -e
if [ ! -d "/lib/modules/$(uname -r)/updates/" ]
then
	mkdir "/lib/modules/$(uname -r)/updates/"
fi
cp -f /usr/lib/modules/*.ko "/lib/modules/$(uname -r)/updates/"

#echo "Running depmod, please wait ..."
#depmod -A
#echo "done running depmod"

deps=()

function findDeps()
{
	unset deps
	deps=()
	while read line
	do
		if [[ -n $line ]]
		then
			for dep in $(echo $line | tr "," "\n")
			do
				deps+=("${dep}")
			done
		fi
	done < <(lsmod | grep -e "$1" | awk -v mod="$1" {' if($1 == mod) print $4'})
	return 0
}

function unloadmod()
{
	deps=()
	findDeps "${1%%.ko}"
	for localdep in "${deps[@]}"
	do
		echo -e "\e[31m\e[5m[Unloading Depedent]\e[0m  $localdep -> $1 ..."
		unloadmod "$localdep"
	done
	rmmod "${1}"
	return $?
}

#echo "loading modules ..."

#keeping the order is important ....
allmods=("axiom_mem_manager.ko" "axiom_mem_dev.ko" "axiom_netdev.ko")
for mod in  "${allmods[@]}"
do
#	kmod=${file%%.ko}
#	kmod=${kmod##*/}
	lsmod | grep -e "${mod%%.ko}" &>/dev/zero
	if [[ $? == 0 ]]
	then
		echo -e "\e[31m\e[5m[Unloading]\e[0m  ${mod} ..."
		unloadmod "${mod%%.ko}"
	fi
	echo -e "\e[33m\e[5m[Loading]\e[0m    ${mod} ..."
	insmod "/usr/lib/modules/${mod}"
	if [[ $? == 0 ]]
	then
		echo -e "\e[32m\e[5m[Done Loading]\e[0m  ${mod} ..."
	else
		echo -e "\e[31m\e[5m[Error Loading]\e[0m ${mod} ..."
	fi
done
echo "[done] loading modules"
