#!/bin/bash

# remove the old axiom package to save space installing the updated one

echo -e "\e[31m\e[5m[Removing]\e[0m  old axiom package to save space ..."

apt-get -y --purge remove axiom

if [[ $? == 0 ]]
then
	echo -e "\e[32m\e[5m[Done]\e[0m  removing old axiom package ..."
else
	echo -e "\e[31m\e[5m[Error]\e[0m removing old axiom package ..."
fi
